# Generated by Django 3.2.5 on 2021-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
