# Generated by Django 3.2.5 on 2021-07-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0008_alter_walk_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='user',
        ),
    ]
