# Generated by Django 3.2.5 on 2021-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkers', '0001_initial'),
        ('walks', '0009_remove_walk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='walker',
        ),
        migrations.AddField(
            model_name='walk',
            name='walker',
            field=models.ManyToManyField(to='walkers.Walker'),
        ),
    ]
