# Generated by Django 3.2.5 on 2021-07-16 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210713_0345'),
        ('walkers', '0001_initial'),
        ('walks', '0011_auto_20210715_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='walker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkers.walker'),
        ),
    ]
