# Generated by Django 3.2.5 on 2021-07-16 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walkers', '0001_initial'),
        ('walks', '0012_auto_20210715_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='walker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='walkers.walker'),
        ),
    ]
